"""
This script returns a audio for the video_script generated by llm.
"""
from gtts import gTTS
from process_video_script import find_voiceover_lines
  
def get_script(video_script_file="data/sample_video_script.txt"):
    script = ""
    with open(video_script_file, "r") as file:
        for line in file:
            script += line
    return script

def script_to_voice(voiceover_lines):
    script = ""
    for aSentence in voiceover_lines:
        script  = script + aSentence  + " \n"
    print("##script",script)
    language = "en-gb"
    myobj = gTTS(text=script, lang=language, slow=False)
    myobj.save("mytext2speech.mp3")



def main():
    #script = get_script(video_script_file="data/sample_video_script.txt")
    voiceover_lines = find_voiceover_lines("data/sample_video_script.txt")
    print("~~~~~~~~~~~~",voiceover_lines)
    script_to_voice(voiceover_lines)

if __name__ == "__main__":
    main()