"""
This script returns a image sequence for the video_script generated by llm.
"""
from process_video_script import find_prompts
from generate_image_from_prompt import img_from_prompt

def generate_images(prompts):
    no_of_imgs = 1 #st.number_input("Enter the number of images")
    for prompt in prompts:
        img_name = "image__generated"+str(no_of_imgs)+".jpg"
        no_of_imgs += 1
        img_from_prompt(prompt, img_name)


def main():
    prompts = find_prompts("data/sample_video_script.txt")
    print("~~~~~~~~~~~~",prompts)
    generate_images(prompts=prompts)

if __name__ == "__main__":
    main()